[phases.build]
cmd = "cargo build --release"

[phases.install]
cmds = ["mkdir -p /app", "cp -r static /app/", "cp -r templates /app/", "cp target/release/web-server-report /app/"]

[start]
cmd = "/app/web-server-report"
