# Optimized Nixpacks configuration for Railway
[variables]
NIXPACKS_METADATA = "rust"
RUST_LOG = "info"
TOKIO_THREAD_STACK_SIZE = "4194304"
RAYON_NUM_THREADS = "0"

[phases.setup]
nixPkgs = ["rustc", "cargo", "gcc", "pkg-config", "openssl.dev", "libiconv"]

[phases.build]
cmd = """
export RUSTFLAGS="-C target-cpu=generic -C opt-level=3"
cargo build --release --locked
"""

[start]
cmd = "./target/release/web-server-report"
