[variables]
CARGO_BUILD_JOBS = "4"
CARGO_NET_RETRY = "3"

[phases.setup]
nixPkgs = ["rust", "pkg-config", "openssl"]

[phases.build]
cmd = "cargo build --release --jobs 4"

[phases.install]
dependsOn = ["build"]
cmd = "mkdir -p /app && cp -r static /app/ && cp -r templates /app/ && cp target/release/web-server-report /app/"

[start]
cmd = "/app/web-server-report"
