# Simplified Nixpacks configuration for Railway - Let Nixpacks auto-detect
[variables]
RUST_LOG = "warn"
TOKIO_THREAD_STACK_SIZE = "8388608"
RAYON_NUM_THREADS = "0"
CARGO_REGISTRIES_CRATES_IO_PROTOCOL = "sparse"
CARGO_HTTP_MULTIPLEXING = "true"
CARGO_NET_RETRY = "3"
CARGO_NET_GIT_FETCH_WITH_CLI = "true"
MALLOC_ARENA_MAX = "4"
RUST_BACKTRACE = "0"

# Let Nixpacks auto-detect setup and build phases
# Only override start command via Procfile and railway.json
