function get_translations_data()
{
    const translations_data = {
    // Homepage
    'homepage-title': { vi: 'Trang chủ - Crypto Dashboard', en: 'Homepage - Crypto Dashboard' },
    'welcome-message': { vi: 'Chào mừng đến Crypto Dashboard', en: 'Welcome to Crypto Dashboard' },
    'homepage-description': { vi: 'Theo dõi và phân tích thị trường tiền mã hóa với các công cụ phân tích chuyên nghiệp và dữ liệu thời gian thực', en: 'Track and analyze cryptocurrency markets with professional analysis tools and real-time data' },
    'view-dashboard': { vi: 'Xem Bài phân tích thị trường Crypto mới nhất', en: 'View Latest Crypto Market Analysis' },
    
    // Dashboard card titles
    'btc-price': { vi: 'Giá BTC', en: 'BTC Price' },
    'market-cap': { vi: 'Tổng Vốn Hóa', en: 'Market Capitalization' },
    'volume-24h': { vi: 'Khối Lượng Giao Dịch 24h', en: '24h Trading Volume' },
    'fear-greed-title': { vi: 'Chỉ số Sợ hãi & Tham lam', en: 'Fear & Greed Index' },
    'rsi-btc-title': { vi: 'Chỉ số Sức mạnh Tương đối (RSI 14) - BTC', en: 'Relative Strength Index (RSI 14) - BTC' },
    'create-report': { vi: 'Tạo báo cáo Mới', en: 'Create New Report' },
    'view-report-history': { vi: 'Lịch Sử Báo Cáo', en: 'View Report History' },
    'home': { vi: 'Trang chủ', en: 'Home' },
    'view-report': { vi: 'Xem báo cáo mới nhất', en: 'View the latest report' },
    'print-report': { vi: 'In Báo cáo', en: 'Print Report' },
    'report-display': { vi: 'Hiển thị báo cáo', en: 'Displaying report' },
    'site-title': { vi: 'Toàn Cảnh Thị Trường Tiền Mã Hóa', en: 'Crypto Market Overview' },
    'created-at': { vi: 'Tạo lúc', en: 'Created at' },
    'analysis-summary': { vi: 'Bài phân tích và tổng hợp', en: 'Analysis and summary' },
    'close': { vi: 'Đóng', en: 'Close' },
    'no-report-created': { vi: 'Chưa có báo cáo nào được tạo.', en: 'No reports have been created yet.' },
    'please-upload': { vi: 'Vui lòng sử dụng trang tải lên để tạo báo cáo đầu tiên của bạn.', en: 'Please use the upload page to create your first report.' },
    'whole-market': { vi: 'Toàn bộ thị trường', en: 'Whole market' },
    'loading': { vi: 'Đang tải...', en: 'Loading...' },
    'connection-issue': { vi: 'Lỗi kết nối', en: 'Connection issue' },
    
    // Report List Page
    'report-history-desc': { vi: 'Xem lại các báo cáo đã được tạo trước đây.', en: 'Review previously created reports.' },
    'created-date': { vi: 'Ngày Tạo', en: 'Created Date' },
    'actions': { vi: 'Hành Động', en: 'Actions' },
    'view-details': { vi: 'Xem Chi Tiết', en: 'View Details' },
    'no-reports': { vi: 'Chưa có báo cáo nào', en: 'No reports yet' },
    'create-first-report': { vi: 'Hãy tạo báo cáo đầu tiên của bạn!', en: 'Create your first report!' },
    'showing': { vi: 'Hiển thị', en: 'Showing' },
    'of-total': { vi: 'trong tổng số', en: 'of' },
    'reports': { vi: 'báo cáo', en: 'reports' },
    'total-reports': { vi: 'Tổng Báo Cáo', en: 'Total Reports' },
    'latest-report': { vi: 'Báo Cáo Mới Nhất', en: 'Latest Report' },
    'current-page': { vi: 'Trang Hiện Tại', en: 'Current Page' },
    
    // Disclaimer
    'disclaimer-title': { vi: 'Tuyên bố miễn trừ trách nhiệm:', en: 'Disclaimer:' },
    'disclaimer-body': { vi: 'Nội dung và phân tích trên trang này chỉ mang tính chất tham khảo và không cấu thành lời khuyên đầu tư. Mọi quyết định đầu tư là trách nhiệm của người đọc.', en: 'The content and analysis on this site are for informational purposes only and do not constitute investment advice. All investment decisions are the responsibility of the reader.' },
    'ai-generated-disclaimer': { vi: 'Báo cáo được tạo tự động bởi trí tuệ nhân tạo (AI) dựa trên dữ liệu thị trường thời gian thực. Không đảm bảo tính chính xác tuyệt đối.', en: 'Reports are automatically generated by artificial intelligence (AI) based on real-time market data. Absolute accuracy is not guaranteed.' },
    
    // Navigation
    'report-table-of-contents': { vi: '📋 Mục lục Báo cáo', en: '📋 Report Table of Contents' },
    
    // Fear & Greed / RSI labels
    'extreme-fear': { vi: 'Sợ hãi Tột độ', en: 'Extreme Fear' },
    'fear': { vi: 'Sợ hãi', en: 'Fear' },
    'neutral': { vi: 'Trung lập', en: 'Neutral' },
    'greed': { vi: 'Tham lam', en: 'Greed' },
    'extreme-greed': { vi: 'Tham lam Tột độ', en: 'Extreme Greed' },
    'oversold': { vi: 'Quá bán', en: 'Oversold' },
    'overbought': { vi: 'Quá mua', en: 'Overbought' },
    'bitcoin': { vi: 'Bitcoin', en: 'Bitcoin' },
    'altcoins': { vi: 'Altcoins', en: 'Altcoins' },
    
    // Dashboard status and controls
    'refresh-data': { vi: 'Cập nhật dữ liệu', en: 'Refresh Data' },
    'refreshing': { vi: 'Đang cập nhật...', en: 'Refreshing...' },
    'connecting': { vi: 'Đang kết nối...', en: 'Connecting...' },
    'reconnecting': { vi: 'Đang kết nối lại...', en: 'Reconnecting...' },
    'real-time-connected': { vi: 'Kết nối thời gian thực', en: 'Real-time connected' },
    'connection-lost': { vi: 'Mất kết nối', en: 'Connection lost' },
    'connection-error': { vi: 'Lỗi kết nối', en: 'Connection error' },
    'data-updated': { vi: 'Dữ liệu đã được cập nhật', en: 'Data updated successfully' },
    'refresh-failed': { vi: 'Lỗi cập nhật dữ liệu', en: 'Failed to refresh data' },
    'last-update': { vi: 'Cập nhật lần cuối', en: 'Last updated' },
    'error-loading-data': { vi: 'Lỗi tải dữ liệu', en: 'Error loading data' },
    
    // Market Indicators Component
    'market-indicators-title': { vi: 'Chỉ Số Thị Trường', en: 'Market Indicators' },
    'crypto-market-stats': { vi: 'Thống Kê Thị Trường Crypto', en: 'Crypto Market Statistics' },
    'live-data': { vi: 'Thời gian thực', en: 'Live data' },
    'fear-greed-index': { vi: 'Chỉ Số Sợ Hãi & Tham Lam của thị trường crypto', en: 'Fear & Greed Index of Crypto Market' },
    'btc-dominance': { vi: 'Độ Thống Trị BTC', en: 'BTC Dominance' },
    'btc-market-share': { vi: 'Thị phần BTC', en: 'BTC Market Share' },
    // Market indicators
    'market-indicators-title': { vi: 'Chỉ Số Thị Trường', en: 'Market Indicators' },
    'btc-dominance': { vi: 'Độ Thống Trị BTC', en: 'BTC Dominance' },
    'eth-dominance': { vi: 'Độ Thống Trị ETH', en: 'ETH Dominance' },
    'btc-market-share': { vi: 'Thị phần BTC', en: 'BTC Market Share' },
    'eth-market-share': { vi: 'Thị phần ETH', en: 'ETH Market Share' },
    'active-cryptos': { vi: 'Coin Hoạt Động', en: 'Active Coins' },
    'markets': { vi: 'Sàn Giao Dịch', en: 'Markets' },
    'market-cap-change': { vi: 'Thay Đổi Vốn Hóa', en: 'Market Cap Change' },
    'last-updated': { vi: 'Cập Nhật Lần Cuối', en: 'Last Updated' },
    
    // Binance Widget
    'binance-prices-title': { vi: 'Giá Crypto từ Binance', en: 'Crypto Prices from Binance' },
    
    // Fear & Greed Index classifications
    'extreme-fear': { vi: 'Sợ hãi tột độ', en: 'Extreme Fear' },
    'fear': { vi: 'Sợ hãi', en: 'Fear' },
    'neutral': { vi: 'Trung tính', en: 'Neutral' },
    'greed': { vi: 'Tham lam', en: 'Greed' },
    'extreme-greed': { vi: 'Tham lam tột độ', en: 'Extreme Greed' },
    
    // Fear & Greed Index descriptions
    'extreme-fear-desc': { vi: 'Thị trường đang trong trạng thái sợ hãi tột độ', en: 'Market is in extreme fear state' },
    'fear-desc': { vi: 'Thị trường có xu hướng giảm mạnh', en: 'Market tends to decline strongly' },
    'neutral-desc': { vi: 'Thị trường ổn định, không có xu hướng rõ ràng', en: 'Market is stable with no clear trend' },
    'greed-desc': { vi: 'Thị trường có xu hướng tăng mạnh', en: 'Market tends to rise strongly' },
    'extreme-greed-desc': { vi: 'Thị trường đang trong trạng thái tham lam tột độ', en: 'Market is in extreme greed state' },
    
    'powered-by': { vi: 'Được cung cấp bởi', en: 'Powered by' },
    'websocket-api': { vi: 'API WebSocket', en: 'WebSocket API' },
    
    // Unit translations for large numbers
    'unit-trillion': { vi: ' Nghìn Tỷ', en: ' T' },
    'unit-billion': { vi: ' Tỷ', en: ' B' },
    'unit-million': { vi: ' Triệu', en: ' M' },

    // Market Analytics Page Translations
    'analytics-page-title': { vi: 'Phân Tích Tương Quan Volume & Open Interest - Crypto Dashboard', en: 'Volume & Open Interest Correlation Analytics - Crypto Dashboard' },
    'analytics-title': { vi: 'Phân Tích Tương Quan Volume Spot & Futures', en: 'Spot vs Futures Volume Correlation Analysis' },
    'analytics-subtitle': { vi: 'So sánh tương quan khối lượng giao dịch Spot vs Phái sinh và Vị thế mở (Open Interest) theo thời gian thực từ Binance API', en: 'Real-time comparison of Spot vs Derivatives trading volume and Open Interest directly from Binance API' },
    'analytics-nav-btn': { vi: 'Phân Tích Volume & OI', en: 'Volume & OI Analytics' },
    'analytics-desc': { vi: 'Công cụ phân tích tương quan dòng tiền Spot - Futures, đo lường độ chênh lệch Volume và theo dõi biến động vị thế mở.', en: 'Analyze Spot vs Futures capital flows, volume delta, ratio, and track open interest fluctuations.' },
    'select-symbol': { vi: 'Cặp Tiền:', en: 'Trading Pair:' },
    'custom-symbol': { vi: 'Khác (e.g. SUIUSDT)...', en: 'Custom (e.g. SUIUSDT)...' },
    'timeframe': { vi: 'Khung:', en: 'Timeframe:' },
    'candle-limit': { vi: 'Số lượng nến', en: 'Candle Limit' },
    'auto-refresh': { vi: 'Tự động cập nhật', en: 'Auto Refresh' },
    'manual-refresh': { vi: 'Cập nhật ngay', en: 'Refresh Now' },
    'api-status': { vi: 'Trạng thái API', en: 'API Status' },
    'created-at': { vi: 'tạo lúc', en: 'created at' },
    'engine-title': { vi: 'Động cơ tính toán phân tích:', en: 'Analytics Calculation Engine:' },
    'client-side-note': { vi: 'Toàn bộ dữ liệu được tải và tính toán trực tiếp trên trình duyệt của bạn từ Binance Public API.', en: 'All data is fetched and computed directly in your browser from Binance Public API.' },
    'disclaimer-body': { vi: 'Nội dung và phân tích trên trang này chỉ mang tính chất tham khảo kỹ thuật và không cấu thành lời khuyên đầu tư. Mọi quyết định đầu tư là trách nhiệm của người đọc.', en: 'The content and analysis on this page are for technical reference only and do not constitute investment advice. All investment decisions are the responsibility of the reader.' },
    'fetch-error': { vi: 'Lỗi tải dữ liệu từ Binance API. Vui lòng thử lại!', en: 'Error fetching data from Binance API. Please try again!' },
    'fetching-data': { vi: 'Đang tải dữ liệu từ Binance...', en: 'Fetching data from Binance...' },
    'candles': { vi: 'nến', en: 'candles' },
    'toggle-debug': { vi: 'Mở bảng Debug WebSocket', en: 'Toggle WebSocket Debug Console' },
    'debug-ws': { vi: 'Debug WS', en: 'Debug WS' },

    // Market Overview Cards (KPIs)
    'spot-volume-24h': { vi: 'Spot Vol (24h)', en: 'Spot Vol (24h)' },
    'futures-volume-24h': { vi: 'Futures Vol (24h)', en: 'Futures Vol (24h)' },
    'futures-spot-ratio': { vi: 'Tỷ Lệ Futures / Spot', en: 'Futures / Spot Ratio' },
    'open-interest': { vi: 'Vị Thế Mở (OI)', en: 'Open Interest (OI)' },
    'long-position-card': { vi: 'Vị Thế Long (OI)', en: 'Long Positions (OI)' },
    'short-position-card': { vi: 'Vị Thế Short (OI)', en: 'Short Positions (OI)' },
    'volume-correlation': { vi: 'Tương Quan Volume (Pearson)', en: 'Volume Correlation (Pearson)' },
    'market-state': { vi: 'Trạng Thái Thị Trường', en: 'Market State' },

    // Dynamic KPI Labels
    'buy': { vi: 'Mua', en: 'Buy' },
    'sell': { vi: 'Bán', en: 'Sell' },
    'buy-sell-ratio-label': { vi: 'Tỷ lệ Mua/Bán', en: 'Buy/Sell Ratio' },
    'high-correlation': { vi: 'Đồng thuận cao (Thị trường thực)', en: 'High Alignment (Spot-driven)' },
    'low-correlation': { vi: 'Phân kỳ / Đầu cơ phái sinh', en: 'Divergence (Speculative)' },
    'moderate-correlation': { vi: 'Tương quan trung bình', en: 'Moderate Correlation' },
    'long-buildup': { vi: '🟢 Long Build-up', en: '🟢 Long Build-up' },
    'short-squeeze': { vi: '🟡 Short Squeeze', en: '🟡 Short Squeeze' },
    'short-buildup': { vi: '🔴 Short Build-up', en: '🔴 Short Build-up' },
    'long-liquidation': { vi: '⚪ Long Liquidation', en: '⚪ Long Liquidation' },
    'neutral-state': { vi: '⚪ Neutral', en: '⚪ Neutral' },

    'long-buildup-desc': { vi: 'Giá tăng + Vị thế mở tăng: Dòng tiền mở Long áp đảo', en: 'Price ↑ + OI ↑: Aggressive Long build-up' },
    'short-squeeze-desc': { vi: 'Giá tăng + Vị thế mở giảm: Tăng do Short bị thanh lý/cắt lỗ', en: 'Price ↑ + OI ↓: Rally driven by Short covering' },
    'short-buildup-desc': { vi: 'Giá giảm + Vị thế mở tăng: Dòng tiền mở Short áp đảo', en: 'Price ↓ + OI ↑: Aggressive Short build-up' },
    'long-liquidation-desc': { vi: 'Giá giảm + Vị thế mở giảm: Long bị thanh lý / rời bỏ vị thế', en: 'Price ↓ + OI ↓: Long capitulation & liquidation' },
    'neutral-desc': { vi: 'Thị trường cân bằng hoặc chưa đủ nến để xác định', en: 'Balanced market state or insufficient data' },

    // Debug Console Panel
    'debug-panel-title': { vi: 'Chẩn Đoán & Giám Sát WebSocket Trực Tiếp', en: 'WebSocket Live Stream Diagnostics & Monitor' },
    'btn-reconnect-ws': { vi: 'Kết nối lại WS', en: 'Reconnect WS' },
    'btn-fetch-snapshot': { vi: 'Tải Snapshot', en: 'Fetch Snapshot' },
    'btn-test-tick': { vi: 'Thử nghiệm Tick', en: 'Test Tick' },
    'btn-clear-log': { vi: 'Xóa Nhật ký', en: 'Clear Log' },
    'dbg-spot-stream': { vi: 'Luồng Spot:', en: 'Spot Stream:' },
    'dbg-fut-stream': { vi: 'Luồng Futures:', en: 'Futures Stream:' },
    'dbg-data-buffer': { vi: 'Bộ đệm Dữ liệu:', en: 'Data Buffer:' },
    'dbg-spot-fut-klines': { vi: 'Nến Spot / Fut', en: 'Spot / Fut Klines' },
    'dbg-aligned-items': { vi: 'Chu kỳ Đồng bộ', en: 'Aligned Items' },
    'dbg-render-engine': { vi: 'Động cơ Render:', en: 'Render Engine:' },
    'dbg-renders': { vi: 'Lần Render', en: 'Renders' },
    'dbg-last-update': { vi: 'Cập nhật cuối', en: 'Last Update' },
    'dbg-log-placeholder': { vi: '// Nhật ký WebSocket và động cơ render sẽ xuất hiện tại đây...', en: '// WebSocket and rendering logs will stream here in real time...' },

    // 8 Chart Layer Badges, Titles, Descriptions & Legends
    'chart1-badge': { vi: '1. Giá & Volume', en: '1. Price & Volume' },
    'tab-price-volume': { vi: 'Giá & Khối lượng Song hành (Spot vs Futures)', en: 'Dual Price & Volume (Spot vs Futures)' },
    'chart1-desc': { vi: 'So sánh tổng thanh khoản dòng tiền giao ngay (Spot) và phái sinh (Futures)', en: 'Compare total liquidity between spot and derivatives (futures)' },

    'chart2-badge': { vi: '2. Khớp Lệnh Taker', en: '2. Taker Order Flow' },
    'tab-buy-sell-volume': { vi: 'Khối lượng Mua vs Bán Chủ Động (Taker)', en: 'Taker Buy vs Sell Volume' },
    'chart2-desc': { vi: 'Phân tách chi tiết áp lực Mua chủ động (Taker Buy) và Bán chủ động (Taker Sell)', en: 'Detailed breakdown of aggressive buying (Taker Buy) vs selling (Taker Sell) pressure' },

    'chart3-badge': { vi: '3. Net Delta Nến', en: '3. Candlestick Net Delta' },
    'tab-net-taker-delta': { vi: 'Net Delta Mua/Bán Ròng (Spot & Futures)', en: 'Net Taker Buy/Sell Delta (Spot & Futures)' },
    'chart3-desc': { vi: 'Chênh lệch khối lượng Mua - Bán chủ động (Taker Buy - Sell) từng chu kỳ', en: 'Volume difference between aggressive buys and sells (Taker Buy - Sell) per candle' },

    'chart4-badge': { vi: '4. Tích Lũy CVD', en: '4. Cumulative CVD' },
    'tab-correlation-cvd': { vi: 'Hệ số Tương quan Trượt & CVD Taker', en: 'Rolling Correlation & Taker CVD' },
    'chart4-desc': { vi: 'Pearson Correlation (14 chu kỳ) và Cumulative Volume Delta tích lũy (phát hiện Phân kỳ CVD)', en: '14-period Pearson Correlation and Cumulative Volume Delta (spotting CVD Divergences)' },

    'chart5-badge': { vi: '5. Vị Thế Mở OI', en: '5. Open Interest (OI)' },
    'tab-open-interest': { vi: 'Vị thế mở (Open Interest) & Hành động Giá', en: 'Open Interest (OI) & Price Action' },
    'chart5-desc': { vi: 'Theo dõi tổng lượng hợp đồng phái sinh đang lưu hành (Nhận diện Build-up vs Squeeze)', en: 'Track outstanding derivative contracts (identifying Build-up vs Squeeze)' },

    'chart6-badge': { vi: '6. Tỷ Lệ L/S', en: '6. L/S Ratio' },
    'tab-long-short-ratio': { vi: 'Phân bổ Vị thế & Tỷ lệ Long / Short', en: 'Position Distribution & Long / Short Ratio' },
    'chart6-desc': { vi: 'Tỷ trọng tài khoản Long vs Short và tỷ lệ L/S Ratio theo thời gian (Đo lường Crowd Bias)', en: 'Long vs Short account proportions and L/S Ratio over time (measuring Crowd Bias)' },

    'chart7-badge': { vi: '7. Tỷ Lệ F/S', en: '7. F/S Ratio' },
    'tab-volume-delta': { vi: 'Độ lệch Volume & Tỷ lệ Futures / Spot', en: 'Volume Delta & Futures / Spot Ratio' },
    'chart7-desc': { vi: 'Chênh lệch khối lượng (Futures - Spot) và tỷ số khuếch đại đòn bẩy', en: 'Volume spread (Futures - Spot) and leverage amplification multiple' },

    'chart8-badge': { vi: '8. Thanh Khoản Spot', en: '8. Spot Liquidity' },
    'tab-long-short-spot': { vi: 'Vị thế Long / Short vs Volume Spot', en: 'Long / Short Positions vs Spot Volume' },
    'chart8-desc': { vi: 'Đối chiếu quy mô vị thế Long và Short so với thanh khoản thị trường Spot', en: 'Compare Long and Short position scale against Spot market liquidity' },

    // Chart Legends
    'legend-spot': { vi: 'Spot', en: 'Spot' },
    'legend-futures': { vi: 'Futures', en: 'Futures' },
    'legend-buy': { vi: 'Mua (Buy)', en: 'Buy' },
    'legend-sell': { vi: 'Bán (Sell)', en: 'Sell' },
    'legend-spot-delta': { vi: 'Spot Delta', en: 'Spot Delta' },
    'legend-fut-delta': { vi: 'Fut Delta', en: 'Fut Delta' },
    'legend-corr': { vi: 'Corr (ρ)', en: 'Corr (ρ)' },
    'legend-spot-cvd': { vi: 'Spot CVD', en: 'Spot CVD' },
    'legend-fut-cvd': { vi: 'Fut CVD', en: 'Fut CVD' },
    'legend-oi': { vi: 'OI ($)', en: 'OI ($)' },
    'legend-pct-long': { vi: '% Long', en: '% Long' },
    'legend-pct-short': { vi: '% Short', en: '% Short' },
    'legend-ls-ratio': { vi: 'L/S Ratio', en: 'L/S Ratio' },
    'legend-delta-pos': { vi: 'Delta > 0', en: 'Delta > 0' },
    'legend-fs-ratio': { vi: 'F/S Ratio', en: 'F/S Ratio' },
    'legend-spot-vol': { vi: 'Spot Vol', en: 'Spot Vol' },
    'legend-long-pos': { vi: 'Long Pos', en: 'Long Pos' },
    'legend-short-pos': { vi: 'Short Pos', en: 'Short Pos' },

    // Period Breakdown Data Table
    'data-breakdown-title': { vi: 'Bảng Thống Kê Chi Tiết Từng Chu Kỳ', en: 'Period-by-Period Data Breakdown' },
    'data-breakdown-desc': { vi: 'Dữ liệu đối chiếu chi tiết các chu kỳ nến với phân tách Khối lượng Mua/Bán, Vị thế Long/Short, Ratios và Open Interest', en: 'Granular candlestick comparative data breakdown with Buy/Sell Volume, Long/Short Positions, Ratios and Open Interest' },
    'export-csv': { vi: 'Xuất CSV', en: 'Export CSV' },
    'btn-customize-columns': { vi: 'Tùy Chọn Cột', en: 'Customize Columns' },
    'quick-views-label': { vi: 'Xem nhanh:', en: 'Quick Views:' },
    'preset-standard': { vi: 'Mặc định', en: 'Default' },
    'preset-full': { vi: 'Tất cả (Đầy đủ)', en: 'All (Full)' },
    'preset-ohlc': { vi: 'Giá & Nến OHLC', en: 'Price & OHLC' },
    'preset-flow': { vi: 'Dòng Tiền & CVD', en: 'Order Flow & CVD' },
    'preset-positions': { vi: 'Vị Thế & OI', en: 'Position & OI' },
    'select-all-columns': { vi: 'Chọn tất cả', en: 'Select All' },
    'reset-columns-default': { vi: 'Khôi phục mặc định', en: 'Reset to Default' },
    'clear-all-columns': { vi: 'Bỏ chọn hết', en: 'Clear All' },
    'column-group-price': { vi: 'Giá & Nến', en: 'Price & Candlestick' },
    'column-group-flow': { vi: 'Khối Lượng & Dòng Tiền Taker', en: 'Volume & Taker Flow' },
    'column-group-positions': { vi: 'Vị Thế & Đòn Bẩy', en: 'Positions & Leverage' },
    'column-group-market': { vi: 'OI & Trạng Thái Thị Trường', en: 'OI & Market State' },
    'th-time': { vi: 'Thời gian', en: 'Time' },
    'th-close-price': { vi: 'Giá Đóng Cửa', en: 'Close Price' },
    'th-ohlc': { vi: 'Nến OHLC ($)', en: 'Candle OHLC ($)' },
    'th-spot-vol': { vi: 'Spot Vol ($)', en: 'Spot Vol ($)' },
    'th-spot-buy-sell': { vi: 'Spot Mua / Bán', en: 'Spot Buy / Sell' },
    'th-spot-delta': { vi: 'Spot Net Delta', en: 'Spot Net Delta' },
    'th-fut-vol': { vi: 'Futures Vol ($)', en: 'Futures Vol ($)' },
    'th-fut-buy-sell': { vi: 'Fut Mua / Bán', en: 'Fut Buy / Sell' },
    'th-fut-delta': { vi: 'Fut Net Delta', en: 'Fut Net Delta' },
    'th-cvd': { vi: 'Spot & Fut CVD', en: 'Spot & Fut CVD' },
    'th-long-pos': { vi: 'Vị thế Long ($)', en: 'Long Pos ($)' },
    'th-short-pos': { vi: 'Vị thế Short ($)', en: 'Short Pos ($)' },
    'th-net-pos': { vi: 'Vị thế Net ($)', en: 'Net Pos ($)' },
    'th-long-spot': { vi: 'Long / Spot', en: 'Long / Spot' },
    'th-short-spot': { vi: 'Short / Spot', en: 'Short / Spot' },
    'th-ls-ratio': { vi: 'Tỷ lệ L/S', en: 'L/S Ratio' },
    'th-fs-ratio': { vi: 'Tỷ lệ F/S', en: 'F/S Ratio' },
    'th-oi-change': { vi: 'Biến động OI (%)', en: 'OI Change (%)' },
    'th-correlation': { vi: 'Tương quan (14)', en: 'Correlation (14)' },
    'table-rows-showing': { vi: 'Số chu kỳ hiển thị:', en: 'Rows showing:' },
    'table-layout-label': { vi: 'Kiểu hiển thị:', en: 'Layout Style:' },
    'table-layout-stacked': { vi: 'Nhóm xuống hàng (Gọn)', en: 'Stacked (Compact)' },
    'table-layout-expanded': { vi: 'Từng cột riêng (Chi tiết)', en: 'Expanded Columns' },
    'th-group-time-state': { vi: 'Thời Gian & Trạng Thái', en: 'Time & State' },
    'th-group-price-range': { vi: 'Giá & Dải Nến (OHLC)', en: 'Price & Candle (OHLC)' },
    'th-group-spot-flow': { vi: 'Spot Vol & Taker Flow', en: 'Spot Vol & Taker Flow' },
    'th-group-fut-flow': { vi: 'Futures Vol & Taker Flow', en: 'Futures Vol & Taker Flow' },
    'th-group-positions': { vi: 'Vị Thế Long / Short & Tỷ Lệ', en: 'Positions & Ratios' },
    'th-group-oi-corr': { vi: 'Vị Thế Mở (OI) & Tương Quan', en: 'Open Interest & Correlation' },

    // Order Flow Playbook & Methodology Guide
    'methodology-title': { vi: 'Cẩm Nang Phân Tích & Hướng Dẫn Đọc Lệnh (Order Flow Guide)', en: 'Order Flow & Market Analysis Playbook' },
    'playbook-title': { vi: 'Quy Trình 4 Bước Đọc Lệnh Thực Chiến (Order Flow Execution)', en: '4-Step Tactical Order Flow Execution Playbook' },
    'step-1-badge': { vi: 'BƯỚC 1', en: 'STEP 1' },
    'step-1-title': { vi: 'Xác Định Lực Khớp Tức Thời', en: 'Determine Real-Time Taker Flow' },
    'step-1-desc': { vi: 'Quan sát biểu đồ Khối lượng Mua vs Bán và Net Delta Nến. Nếu Net Delta dương đậm (Xanh lá) nghĩa là phe Mua đang chủ động đẩy lệnh Market; nếu âm (Đỏ) là phe Bán đang ép giá.', en: 'Observe Buy vs Sell Volume and Candlestick Net Delta. A strong positive Net Delta (Green) signals buyers aggressively hitting market orders; negative (Red) indicates aggressive sellers dumping.' },
    'step-2-badge': { vi: 'BƯỚC 2', en: 'STEP 2' },
    'step-2-title': { vi: 'Đối Chiếu Vị Thế Mở (OI)', en: 'Cross-Reference Open Interest (OI)' },
    'step-2-desc': { vi: 'Kiểm tra biến động OI: Giá tăng mà OI tăng là tiền mới vào mở Long (Long Build-up). Nếu Giá tăng mà OI giảm thì chỉ là Short bị thanh lý/cắt lỗ (Short Squeeze - rủi ro đảo chiều cao).', en: 'Check OI dynamics: Price ↑ + OI ↑ indicates fresh capital accumulating Longs (Long Build-up). Price ↑ + OI ↓ indicates short liquidations/stop-losses (Short Squeeze - high reversal risk).' },
    'step-3-badge': { vi: 'BƯỚC 3', en: 'STEP 3' },
    'step-3-title': { vi: 'Phát Hiện Phân Kỳ CVD', en: 'Spot CVD Divergences' },
    'step-3-desc': { vi: 'Nếu Giá tạo đáy mới thấp hơn nhưng đường CVD tạo đáy cao hơn -> Phe Bán bị hấp thụ hoàn toàn bởi lệnh Limit Buy (Tín hiệu đảo chiều tăng mạnh).', en: 'If Price makes a lower low while CVD makes a higher low -> Sellers are completely absorbed by Limit Buy orders (Strong bullish reversal signal).' },
    'step-4-badge': { vi: 'BƯỚC 4', en: 'STEP 4' },
    'step-4-title': { vi: 'Đánh Giá Đòn Bẩy F/S', en: 'Evaluate F/S Leverage Ratio' },
    'step-4-desc': { vi: 'Tỷ lệ Futures/Spot > 4x cảnh báo thị trường đầu cơ quá mức. Đối chiếu quy mô Long/Short với Spot Vol để phòng ngừa rủi ro bẫy quét thanh lý 2 đầu.', en: 'Futures/Spot ratio > 4x warns of excessive speculative leverage. Cross-reference Long/Short sizes against Spot Vol to guard against two-way liquidation wicks.' },

    // Cheat Sheet Matrix
    'cheat-sheet-title': { vi: 'Bảng Tra Cứu Tín Hiệu & Hành Động Đọc Lệnh Nhanh', en: 'Quick Signal & Action Cheat-Sheet Matrix' },
    'th-state': { vi: 'Trạng Thái', en: 'State' },
    'th-price': { vi: 'Giá (Price)', en: 'Price' },
    'th-taker-flow': { vi: 'Taker Flow', en: 'Taker Flow' },
    'th-oi': { vi: 'Vị Thế Mở (OI)', en: 'Open Interest (OI)' },
    'th-nature': { vi: 'Bản Chất Dòng Tiền', en: 'Flow Dynamics' },
    'th-action': { vi: 'Hành Động Khuyến Nghị', en: 'Recommended Action' },

    'long-buildup-state': { vi: '🟢 Long Build-up', en: '🟢 Long Build-up' },
    'short-squeeze-state': { vi: '🟡 Short Squeeze', en: '🟡 Short Squeeze' },
    'short-buildup-state': { vi: '🔴 Short Build-up', en: '🔴 Short Build-up' },
    'long-liquidation-state': { vi: '⚪ Long Liquidation', en: '⚪ Long Liquidation' },

    'flow-price-up': { vi: 'Tăng (↑)', en: 'Rising (↑)' },
    'flow-price-down': { vi: 'Giảm (↓)', en: 'Falling (↓)' },
    'flow-buy-up': { vi: 'Mua chủ động ↑', en: 'Aggressive Buy ↑' },
    'flow-sell-up': { vi: 'Bán chủ động ↑', en: 'Aggressive Sell ↑' },
    'flow-oi-surge-up': { vi: 'Tăng mạnh (↑)', en: 'Surging (↑)' },
    'flow-oi-drop-down': { vi: 'Giảm mạnh (↓)', en: 'Dumping (↓)' },

    'long-buildup-nature': { vi: 'Dòng tiền tổ chức/trader nạp vốn mở vị thế Long mới theo xu hướng', en: 'Institutional/trader capital entering fresh Long positions with the trend' },
    'long-buildup-action': { vi: 'Ưu tiên Buy / Long theo Trend', en: 'Prioritize Buy / Long with Trend' },
    'short-squeeze-nature': { vi: 'Tăng do phe Short bị ép cắt lỗ hoặc thanh lý cưỡng bức (Hết xăng)', en: 'Rally driven by short liquidations & stop-loss cascades (Exhaustion)' },
    'short-squeeze-action': { vi: 'Chốt lời Long, canh Short đảo chiều', en: 'Take profit Long, prepare for Short reversal' },
    'short-buildup-nature': { vi: 'Dòng tiền mở mới vị thế Short ồ ạt, áp lực bán đè giá quyết liệt', en: 'Heavy aggressive Short positions opened, heavy selling pressure pushing price down' },
    'short-buildup-action': { vi: 'Ưu tiên Sell / Short theo Trend', en: 'Prioritize Sell / Short with Trend' },
    'long-liquidation-nature': { vi: 'Long bị xả thanh lý hàng loạt, giai đoạn rũ bỏ cuối cùng của đợt giảm', en: 'Long positions liquidated in cascades, final capitulation / shakeout phase' },
    'long-liquidation-action': { vi: 'Chốt lời Short, canh bắt đáy hồi phục', en: 'Take profit Short, look for mean-reversion bounce' },

    // Metric Details Grid
    'metrics-detail-title': { vi: 'Ý Nghĩa & Chi Tiết Các Chỉ Số Đo Lường', en: 'Key Metric Definitions & Theoretical Details' },
    'card-taker-title': { vi: '📊 Taker Buy / Sell Volume', en: '📊 Taker Buy / Sell Volume' },
    'taker-desc': { vi: 'Đo lường trực tiếp các lệnh khớp Market. Taker Buy bao gồm mở Long mới + cắt lỗ Short; Taker Sell bao gồm mở Short mới + thanh lý Long.', en: 'Directly measures executed market orders. Taker Buy includes fresh Longs + Short stops; Taker Sell includes fresh Shorts + Long liquidations.' },
    'card-cvd-title': { vi: '📈 Cumulative Volume Delta (CVD)', en: '📈 Cumulative Volume Delta (CVD)' },
    'cvd-desc': { vi: 'Tích lũy chênh lệch (Buy - Sell). CVD phân kỳ với giá là chỉ báo sớm đáng tin cậy nhất về việc cá mập đang âm thầm gom hoặc xả hàng.', en: 'Cumulative difference of (Buy - Sell). CVD divergence against price is the most reliable leading indicator of smart-money accumulation or distribution.' },
    'card-ls-ratio-title': { vi: '⚖️ Long / Short Position Ratio', en: '⚖️ Long / Short Position Ratio' },
    'ls-pos-desc': { vi: 'Tỷ lệ tài khoản hoặc vị thế mở Long vs Short. Tỷ lệ lệch trên 70% là tín hiệu thị trường quá nghiêng về một phía (Crowded Trade), dễ xảy ra bẫy quét thanh lý.', en: 'Ratio of Long vs Short accounts/positions. A skew exceeding 70% indicates a crowded trade, highly vulnerable to liquidation cascades.' },
    'card-long-spot-title': { vi: '📈 Long / Spot Vol Ratio', en: '📈 Long / Spot Vol Ratio' },
    'long-spot-desc': { vi: 'Đo lường quy mô vị thế Long so với thanh khoản Spot. Tỷ lệ > 3x - 5x cảnh báo thanh khoản Spot có thể không hấp thụ nổi nếu xảy ra chuỗi thanh lý Long đột ngột.', en: 'Measures Long position notional size against Spot liquidity. A ratio > 3x - 5x warns that Spot depth may fail to absorb cascading Long liquidations.' },
    'card-short-spot-title': { vi: '📉 Short / Spot Vol Ratio', en: '📉 Short / Spot Vol Ratio' },
    'short-spot-desc': { vi: 'Đo lường quy mô vị thế Short so với thanh khoản Spot. Tỷ lệ > 3x - 5x là tín hiệu cảnh báo rủi ro bùng nổ Short Squeeze cực mạnh khi giá đảo chiều tăng.', en: 'Measures Short position notional size against Spot liquidity. A ratio > 3x - 5x warns of explosive Short Squeezes upon price reversal.' },
    'card-corr-title': { vi: '🔗 Pearson Volume Correlation', en: '🔗 Pearson Volume Correlation' },
    'corr-desc': { vi: 'Hệ số tương quan khối lượng giữa Spot và Futures (14 chu kỳ). > 0.7 thể hiện dòng tiền thực giao ngay đồng thuận; < 0.3 là dấu hiệu đầu cơ phái sinh đơn lẻ.', en: 'Rolling 14-period volume correlation between Spot and Futures. > 0.7 reflects genuine spot market alignment; < 0.3 indicates isolated derivatives speculation.' },

    // WebSocket / Realtime status
    'websocket-status': { vi: 'WebSocket Thời gian thực', en: 'Real-time WebSocket' },
    'live-stream': { vi: 'Dữ liệu Trực tiếp', en: 'Live Stream' },
    'ws-connected': { vi: 'Kết nối WebSocket thành công', en: 'WebSocket Connected' },
    'ws-reconnecting': { vi: 'Đang kết nối lại WebSocket...', en: 'Reconnecting WebSocket...' },
    'ws-disconnected': { vi: 'Mất kết nối WebSocket', en: 'WebSocket Disconnected' },
    'ws-live': { vi: 'Trực tiếp (Live)', en: 'Live Stream' }
    };
    return translations_data;
}

// Auto-register translations when this script loads
(function() {
    // Function to try registering translations
    function tryRegisterTranslations() {
        try {
            const translationsData = get_translations_data();
            
            // Method 1: Use setTranslations if available
            if (typeof window.setTranslations === 'function') {
                window.setTranslations(translationsData);
                console.log('✅ Translations registered via setTranslations');
                return true;
            }
            
            // Method 2: Set global variables directly
            window.translations_data = translationsData;
            window.translations = translationsData;
            console.log('✅ Translations set globally');
            
            return false; // setTranslations not available yet
        } catch (e) {
            console.warn('Could not register translations:', e);
            return false;
        }
    }
    
    // Try immediately first
    if (tryRegisterTranslations()) {
        return; // Success, we're done
    }
    
    // If failed, wait for DOM ready and retry
    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', function() {
            setTimeout(tryRegisterTranslations, 100);
        });
    } else {
        // DOM already ready, retry after a short delay
        setTimeout(tryRegisterTranslations, 100);
    }
    
    // Also listen for a custom event in case language-toggle.js loads later
    window.addEventListener('languageToggleReady', function() {
        tryRegisterTranslations();
    });
})();

