function get_translations_data()
{
    const translations_data = {
    // Homepage
    'homepage-title': { vi: 'Trang chủ - Crypto Dashboard', en: 'Homepage - Crypto Dashboard' },
    'welcome-message': { vi: 'Chào mừng đến Crypto Dashboard', en: 'Welcome to Crypto Dashboard' },
    'homepage-description': { vi: 'Theo dõi và phân tích thị trường tiền mã hóa với các công cụ phân tích chuyên nghiệp và dữ liệu thời gian thực', en: 'Track and analyze cryptocurrency markets with professional analysis tools and real-time data' },
    'view-dashboard': { vi: 'Xem Bài phân tích thị trường Crypto mới nhất', en: 'View Latest Crypto Market Analysis' },
    
    // Dashboard card titles
    'btc-price': { vi: 'Giá BTC', en: 'BTC Price' },
    'market-cap': { vi: 'Tổng Vốn Hóa', en: 'Market Capitalization' },
    'volume-24h': { vi: 'Khối Lượng Giao Dịch 24h', en: '24h Trading Volume' },
    'fear-greed-title': { vi: 'Chỉ số Sợ hãi & Tham lam', en: 'Fear & Greed Index' },
    'rsi-btc-title': { vi: 'Chỉ số Sức mạnh Tương đối (RSI 14) - BTC', en: 'Relative Strength Index (RSI 14) - BTC' },
    'create-report': { vi: 'Tạo báo cáo Mới', en: 'Create New Report' },
    'view-report-history': { vi: 'Lịch Sử Báo Cáo', en: 'View Report History' },
    'home': { vi: 'Trang chủ', en: 'Home' },
    'view-report': { vi: 'Xem báo cáo mới nhất', en: 'View the latest report' },
    'print-report': { vi: 'In Báo cáo', en: 'Print Report' },
    'report-display': { vi: 'Hiển thị báo cáo', en: 'Displaying report' },
    'site-title': { vi: 'Toàn Cảnh Thị Trường Tiền Mã Hóa', en: 'Crypto Market Overview' },
    'created-at': { vi: 'Tạo lúc', en: 'Created at' },
    'analysis-summary': { vi: 'Bài phân tích và tổng hợp', en: 'Analysis and summary' },
    'close': { vi: 'Đóng', en: 'Close' },
    'no-report-created': { vi: 'Chưa có báo cáo nào được tạo.', en: 'No reports have been created yet.' },
    'please-upload': { vi: 'Vui lòng sử dụng trang tải lên để tạo báo cáo đầu tiên của bạn.', en: 'Please use the upload page to create your first report.' },
    'whole-market': { vi: 'Toàn bộ thị trường', en: 'Whole market' },
    'loading': { vi: 'Đang tải...', en: 'Loading...' },
    'connection-issue': { vi: 'Lỗi kết nối', en: 'Connection issue' },
    
    // Report List Page
    'report-history-desc': { vi: 'Xem lại các báo cáo đã được tạo trước đây.', en: 'Review previously created reports.' },
    'created-date': { vi: 'Ngày Tạo', en: 'Created Date' },
    'actions': { vi: 'Hành Động', en: 'Actions' },
    'view-details': { vi: 'Xem Chi Tiết', en: 'View Details' },
    'no-reports': { vi: 'Chưa có báo cáo nào', en: 'No reports yet' },
    'create-first-report': { vi: 'Hãy tạo báo cáo đầu tiên của bạn!', en: 'Create your first report!' },
    'showing': { vi: 'Hiển thị', en: 'Showing' },
    'of-total': { vi: 'trong tổng số', en: 'of' },
    'reports': { vi: 'báo cáo', en: 'reports' },
    'total-reports': { vi: 'Tổng Báo Cáo', en: 'Total Reports' },
    'latest-report': { vi: 'Báo Cáo Mới Nhất', en: 'Latest Report' },
    'current-page': { vi: 'Trang Hiện Tại', en: 'Current Page' },
    
    // Disclaimer
    'disclaimer-title': { vi: 'Tuyên bố miễn trừ trách nhiệm:', en: 'Disclaimer:' },
    'disclaimer-body': { vi: 'Nội dung và phân tích trên trang này chỉ mang tính chất tham khảo và không cấu thành lời khuyên đầu tư. Mọi quyết định đầu tư là trách nhiệm của người đọc.', en: 'The content and analysis on this site are for informational purposes only and do not constitute investment advice. All investment decisions are the responsibility of the reader.' },
    'ai-generated-disclaimer': { vi: 'Báo cáo được tạo tự động bởi trí tuệ nhân tạo (AI) dựa trên dữ liệu thị trường thời gian thực. Không đảm bảo tính chính xác tuyệt đối.', en: 'Reports are automatically generated by artificial intelligence (AI) based on real-time market data. Absolute accuracy is not guaranteed.' },
    
    // Navigation
    'report-table-of-contents': { vi: '📋 Mục lục Báo cáo', en: '📋 Report Table of Contents' },
    
    // Fear & Greed / RSI labels
    'extreme-fear': { vi: 'Sợ hãi Tột độ', en: 'Extreme Fear' },
    'fear': { vi: 'Sợ hãi', en: 'Fear' },
    'neutral': { vi: 'Trung lập', en: 'Neutral' },
    'greed': { vi: 'Tham lam', en: 'Greed' },
    'extreme-greed': { vi: 'Tham lam Tột độ', en: 'Extreme Greed' },
    'oversold': { vi: 'Quá bán', en: 'Oversold' },
    'overbought': { vi: 'Quá mua', en: 'Overbought' },
    'bitcoin': { vi: 'Bitcoin', en: 'Bitcoin' },
    'altcoins': { vi: 'Altcoins', en: 'Altcoins' },
    
    // Dashboard status and controls
    'refresh-data': { vi: 'Cập nhật dữ liệu', en: 'Refresh Data' },
    'refreshing': { vi: 'Đang cập nhật...', en: 'Refreshing...' },
    'connecting': { vi: 'Đang kết nối...', en: 'Connecting...' },
    'reconnecting': { vi: 'Đang kết nối lại...', en: 'Reconnecting...' },
    'real-time-connected': { vi: 'Kết nối thời gian thực', en: 'Real-time connected' },
    'connection-lost': { vi: 'Mất kết nối', en: 'Connection lost' },
    'connection-error': { vi: 'Lỗi kết nối', en: 'Connection error' },
    'data-updated': { vi: 'Dữ liệu đã được cập nhật', en: 'Data updated successfully' },
    'refresh-failed': { vi: 'Lỗi cập nhật dữ liệu', en: 'Failed to refresh data' },
    'last-update': { vi: 'Cập nhật lần cuối', en: 'Last updated' },
    'error-loading-data': { vi: 'Lỗi tải dữ liệu', en: 'Error loading data' },
    
    // Market Indicators Component
    'market-indicators-title': { vi: 'Chỉ Số Thị Trường', en: 'Market Indicators' },
    'crypto-market-stats': { vi: 'Thống Kê Thị Trường Crypto', en: 'Crypto Market Statistics' },
    'live-data': { vi: 'Thời gian thực', en: 'Live data' },
    'fear-greed-index': { vi: 'Chỉ Số Sợ Hãi & Tham Lam của thị trường crypto', en: 'Fear & Greed Index of Crypto Market' },
    'btc-dominance': { vi: 'Độ Thống Trị BTC', en: 'BTC Dominance' },
    'btc-market-share': { vi: 'Thị phần BTC', en: 'BTC Market Share' },
    // Market indicators
    'market-indicators-title': { vi: 'Chỉ Số Thị Trường', en: 'Market Indicators' },
    'btc-dominance': { vi: 'Độ Thống Trị BTC', en: 'BTC Dominance' },
    'eth-dominance': { vi: 'Độ Thống Trị ETH', en: 'ETH Dominance' },
    'btc-market-share': { vi: 'Thị phần BTC', en: 'BTC Market Share' },
    'eth-market-share': { vi: 'Thị phần ETH', en: 'ETH Market Share' },
    'active-cryptos': { vi: 'Coin Hoạt Động', en: 'Active Coins' },
    'markets': { vi: 'Sàn Giao Dịch', en: 'Markets' },
    'market-cap-change': { vi: 'Thay Đổi Vốn Hóa', en: 'Market Cap Change' },
    'last-updated': { vi: 'Cập Nhật Lần Cuối', en: 'Last Updated' },
    
    // Binance Widget
    'binance-prices-title': { vi: 'Giá Crypto từ Binance', en: 'Crypto Prices from Binance' },
    
    // Fear & Greed Index classifications
    'extreme-fear': { vi: 'Sợ hãi tột độ', en: 'Extreme Fear' },
    'fear': { vi: 'Sợ hãi', en: 'Fear' },
    'neutral': { vi: 'Trung tính', en: 'Neutral' },
    'greed': { vi: 'Tham lam', en: 'Greed' },
    'extreme-greed': { vi: 'Tham lam tột độ', en: 'Extreme Greed' },
    
    // Fear & Greed Index descriptions
    'extreme-fear-desc': { vi: 'Thị trường đang trong trạng thái sợ hãi tột độ', en: 'Market is in extreme fear state' },
    'fear-desc': { vi: 'Thị trường có xu hướng giảm mạnh', en: 'Market tends to decline strongly' },
    'neutral-desc': { vi: 'Thị trường ổn định, không có xu hướng rõ ràng', en: 'Market is stable with no clear trend' },
    'greed-desc': { vi: 'Thị trường có xu hướng tăng mạnh', en: 'Market tends to rise strongly' },
    'extreme-greed-desc': { vi: 'Thị trường đang trong trạng thái tham lam tột độ', en: 'Market is in extreme greed state' },
    
    'powered-by': { vi: 'Được cung cấp bởi', en: 'Powered by' },
    'websocket-api': { vi: 'API WebSocket', en: 'WebSocket API' },
    'us-stock-indices': { vi: 'Chỉ Số Chứng Khoán Mỹ', en: 'US Stock Indices' },
    
    // Unit translations for large numbers
    'unit-trillion': { vi: ' Nghìn Tỷ', en: ' T' },
    'unit-billion': { vi: ' Tỷ', en: ' B' },
    'unit-million': { vi: ' Triệu', en: ' M' },

    // Market Analytics Page Translations
    'analytics-page-title': { vi: 'Phân Tích Tương Quan Volume & Open Interest - Crypto Dashboard', en: 'Volume & Open Interest Correlation Analytics - Crypto Dashboard' },
    'analytics-title': { vi: 'Phân Tích Tương Quan Volume Spot & Futures', en: 'Spot vs Futures Volume & Open Interest Analytics' },
    'analytics-subtitle': { vi: 'So sánh tương quan khối lượng giao dịch Spot vs Phái sinh và Vị thế mở (Open Interest) theo thời gian thực từ Binance API', en: 'Real-time correlation analysis of Spot vs Derivatives trading volume and Open Interest directly from Binance API' },
    'analytics-nav-btn': { vi: 'Phân Tích Volume & Vị Thế Mở (OI)', en: 'Volume & Open Interest Analytics' },
    'analytics-desc': { vi: 'Công cụ phân tích tương quan dòng tiền Spot - Futures, đo lường độ chênh lệch Volume và theo dõi biến động vị thế mở.', en: 'Analyze Spot vs Futures capital flows, volume delta, ratio, and track open interest fluctuations.' },
    'select-symbol': { vi: 'Chọn Cặp Giao Dịch', en: 'Select Trading Pair' },
    'custom-symbol': { vi: 'Nhập cặp khác...', en: 'Custom pair (e.g. SOLUSDT)...' },
    'timeframe': { vi: 'Khung thời gian', en: 'Timeframe' },
    'candle-limit': { vi: 'Số lượng nến', en: 'Candle Limit' },
    'auto-refresh': { vi: 'Tự động cập nhật', en: 'Auto Refresh' },
    'manual-refresh': { vi: 'Cập nhật ngay', en: 'Refresh Now' },
    'api-status': { vi: 'Trạng thái API', en: 'API Status' },
    'spot-volume-24h': { vi: 'Khối lượng Spot (24h)', en: '24h Spot Volume' },
    'futures-volume-24h': { vi: 'Khối lượng Futures (24h)', en: '24h Futures Volume' },
    'futures-spot-ratio': { vi: 'Tỷ lệ Futures / Spot', en: 'Futures / Spot Ratio' },
    'open-interest': { vi: 'Vị thế mở (Open Interest)', en: 'Open Interest (OI)' },
    'volume-correlation': { vi: 'Tương quan Volume (Pearson)', en: 'Volume Correlation (Pearson)' },
    'market-state': { vi: 'Trạng thái thị trường', en: 'Market State' },
    'high-correlation': { vi: 'Đồng thuận cao (Thị trường thực)', en: 'High Alignment (Spot-driven)' },
    'low-correlation': { vi: 'Phân kỳ / Đầu cơ phái sinh', en: 'Divergence (Speculative)' },
    'moderate-correlation': { vi: 'Tương quan trung bình', en: 'Moderate Correlation' },
    'long-buildup': { vi: 'Long Tích lũy (Giá ↑, OI ↑)', en: 'Long Build-up (Price ↑, OI ↑)' },
    'short-squeeze': { vi: 'Short Squeeze (Giá ↑, OI ↓)', en: 'Short Squeeze (Price ↑, OI ↓)' },
    'short-buildup': { vi: 'Short Tích lũy (Giá ↓, OI ↑)', en: 'Short Build-up (Price ↓, OI ↑)' },
    'long-liquidation': { vi: 'Long Thanh lý (Giá ↓, OI ↓)', en: 'Long Liquidation (Price ↓, OI ↓)' },
    'tab-price-volume': { vi: 'Giá & Khối lượng Song hành', en: 'Price & Dual Volume' },
    'tab-volume-delta': { vi: 'Độ lệch Volume & Tỷ lệ F/S', en: 'Volume Delta & Ratio' },
    'tab-open-interest': { vi: 'Vị thế mở & Giá', en: 'Open Interest & Price' },
    'tab-correlation-cvd': { vi: 'Tương quan & CVD', en: 'Correlation & CVD' },
    'data-breakdown-title': { vi: 'Bảng Thống Kê Chi Tiết Từng Chu Kỳ', en: 'Period-by-Period Data Breakdown' },
    'export-csv': { vi: 'Xuất dữ liệu (CSV)', en: 'Export to CSV' },
    'methodology-title': { vi: 'Hướng dẫn Phân tích & Ý nghĩa Chỉ số', en: 'Methodology & Indicator Interpretation' },
    'client-side-note': { vi: '⚡ Toàn bộ dữ liệu được tải và tính toán trực tiếp trên trình duyệt của bạn từ Binance Public API.', en: '⚡ All data is fetched and computed directly in your browser from Binance Public APIs.' },
    'fetch-error': { vi: 'Lỗi tải dữ liệu từ Binance API. Vui lòng thử lại!', en: 'Error fetching data from Binance API. Please try again!' },
    'fetching-data': { vi: 'Đang tải dữ liệu từ Binance...', en: 'Fetching data from Binance...' },
    'candles': { vi: 'nến', en: 'candles' }
    };
    return translations_data;
}

// Auto-register translations when this script loads
(function() {
    // Function to try registering translations
    function tryRegisterTranslations() {
        try {
            const translationsData = get_translations_data();
            
            // Method 1: Use setTranslations if available
            if (typeof window.setTranslations === 'function') {
                window.setTranslations(translationsData);
                console.log('✅ Translations registered via setTranslations');
                return true;
            }
            
            // Method 2: Set global variables directly
            window.translations_data = translationsData;
            window.translations = translationsData;
            console.log('✅ Translations set globally');
            
            return false; // setTranslations not available yet
        } catch (e) {
            console.warn('Could not register translations:', e);
            return false;
        }
    }
    
    // Try immediately first
    if (tryRegisterTranslations()) {
        return; // Success, we're done
    }
    
    // If failed, wait for DOM ready and retry
    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', function() {
            setTimeout(tryRegisterTranslations, 100);
        });
    } else {
        // DOM already ready, retry after a short delay
        setTimeout(tryRegisterTranslations, 100);
    }
    
    // Also listen for a custom event in case language-toggle.js loads later
    window.addEventListener('languageToggleReady', function() {
        tryRegisterTranslations();
    });
})();

