function get_translations_data()
{
    const translations_data = {
    // Homepage
    'homepage-title': { vi: 'Trang chủ - Crypto Dashboard', en: 'Homepage - Crypto Dashboard' },
    'welcome-message': { vi: 'Chào mừng đến Crypto Dashboard', en: 'Welcome to Crypto Dashboard' },
    'homepage-description': { vi: 'Theo dõi và phân tích thị trường tiền mã hóa với các công cụ phân tích chuyên nghiệp và dữ liệu thời gian thực', en: 'Track and analyze cryptocurrency markets with professional analysis tools and real-time data' },
    'view-dashboard': { vi: 'Xem Bài phân tích thị trường Crypto mới nhất', en: 'View Latest Crypto Market Analysis' },
    
    // Dashboard card titles
    'btc-price': { vi: 'Giá BTC', en: 'BTC Price' },
    'market-cap': { vi: 'Tổng Vốn Hóa', en: 'Market Capitalization' },
    'volume-24h': { vi: 'Khối Lượng Giao Dịch 24h', en: '24h Trading Volume' },
    'fear-greed-title': { vi: 'Chỉ số Sợ hãi & Tham lam', en: 'Fear & Greed Index' },
    'rsi-btc-title': { vi: 'Chỉ số Sức mạnh Tương đối (RSI 14) - BTC', en: 'Relative Strength Index (RSI 14) - BTC' },
    'create-report': { vi: 'Tạo báo cáo Mới', en: 'Create New Report' },
    'view-report-history': { vi: 'Lịch Sử Báo Cáo', en: 'View Report History' },
    'home': { vi: 'Trang chủ', en: 'Home' },
    'view-report': { vi: 'Xem báo cáo mới nhất', en: 'View the latest report' },
    'print-report': { vi: 'In Báo cáo', en: 'Print Report' },
    'report-display': { vi: 'Hiển thị báo cáo', en: 'Displaying report' },
    'site-title': { vi: 'Toàn Cảnh Thị Trường Tiền Mã Hóa', en: 'Crypto Market Overview' },
    'created-at': { vi: 'Tạo lúc', en: 'Created at' },
    'analysis-summary': { vi: 'Bài phân tích và tổng hợp', en: 'Analysis and summary' },
    'close': { vi: 'Đóng', en: 'Close' },
    'no-report-created': { vi: 'Chưa có báo cáo nào được tạo.', en: 'No reports have been created yet.' },
    'please-upload': { vi: 'Vui lòng sử dụng trang tải lên để tạo báo cáo đầu tiên của bạn.', en: 'Please use the upload page to create your first report.' },
    'whole-market': { vi: 'Toàn bộ thị trường', en: 'Whole market' },
    'loading': { vi: 'Đang tải...', en: 'Loading...' },
    'connection-issue': { vi: 'Lỗi kết nối', en: 'Connection issue' },
    
    // Report List Page
    'report-history-desc': { vi: 'Xem lại các báo cáo đã được tạo trước đây.', en: 'Review previously created reports.' },
    'created-date': { vi: 'Ngày Tạo', en: 'Created Date' },
    'actions': { vi: 'Hành Động', en: 'Actions' },
    'view-details': { vi: 'Xem Chi Tiết', en: 'View Details' },
    'no-reports': { vi: 'Chưa có báo cáo nào', en: 'No reports yet' },
    'create-first-report': { vi: 'Hãy tạo báo cáo đầu tiên của bạn!', en: 'Create your first report!' },
    'showing': { vi: 'Hiển thị', en: 'Showing' },
    'of-total': { vi: 'trong tổng số', en: 'of' },
    'reports': { vi: 'báo cáo', en: 'reports' },
    'total-reports': { vi: 'Tổng Báo Cáo', en: 'Total Reports' },
    'latest-report': { vi: 'Báo Cáo Mới Nhất', en: 'Latest Report' },
    'current-page': { vi: 'Trang Hiện Tại', en: 'Current Page' },
    
    // Disclaimer
    'disclaimer-title': { vi: 'Tuyên bố miễn trừ trách nhiệm:', en: 'Disclaimer:' },
    'disclaimer-body': { vi: 'Nội dung và phân tích trên trang này chỉ mang tính chất tham khảo và không cấu thành lời khuyên đầu tư. Mọi quyết định đầu tư là trách nhiệm của người đọc.', en: 'The content and analysis on this site are for informational purposes only and do not constitute investment advice. All investment decisions are the responsibility of the reader.' },
    'ai-generated-disclaimer': { vi: 'Báo cáo được tạo tự động bởi trí tuệ nhân tạo (AI) dựa trên dữ liệu thị trường thời gian thực. Không đảm bảo tính chính xác tuyệt đối.', en: 'Reports are automatically generated by artificial intelligence (AI) based on real-time market data. Absolute accuracy is not guaranteed.' },
    
    // Navigation
    'report-table-of-contents': { vi: '📋 Mục lục Báo cáo', en: '📋 Report Table of Contents' },
    
    // Fear & Greed / RSI labels
    'extreme-fear': { vi: 'Sợ hãi Tột độ', en: 'Extreme Fear' },
    'fear': { vi: 'Sợ hãi', en: 'Fear' },
    'neutral': { vi: 'Trung lập', en: 'Neutral' },
    'greed': { vi: 'Tham lam', en: 'Greed' },
    'extreme-greed': { vi: 'Tham lam Tột độ', en: 'Extreme Greed' },
    'oversold': { vi: 'Quá bán', en: 'Oversold' },
    'overbought': { vi: 'Quá mua', en: 'Overbought' },
    'bitcoin': { vi: 'Bitcoin', en: 'Bitcoin' },
    'altcoins': { vi: 'Altcoins', en: 'Altcoins' },
    
    // Dashboard status and controls
    'refresh-data': { vi: 'Cập nhật dữ liệu', en: 'Refresh Data' },
    'refreshing': { vi: 'Đang cập nhật...', en: 'Refreshing...' },
    'connecting': { vi: 'Đang kết nối...', en: 'Connecting...' },
    'reconnecting': { vi: 'Đang kết nối lại...', en: 'Reconnecting...' },
    'real-time-connected': { vi: 'Kết nối thời gian thực', en: 'Real-time connected' },
    'connection-lost': { vi: 'Mất kết nối', en: 'Connection lost' },
    'connection-error': { vi: 'Lỗi kết nối', en: 'Connection error' },
    'data-updated': { vi: 'Dữ liệu đã được cập nhật', en: 'Data updated successfully' },
    'refresh-failed': { vi: 'Lỗi cập nhật dữ liệu', en: 'Failed to refresh data' },
    'last-update': { vi: 'Cập nhật lần cuối', en: 'Last updated' },
    'error-loading-data': { vi: 'Lỗi tải dữ liệu', en: 'Error loading data' },
    
    // Market Indicators Component
    'market-indicators-title': { vi: 'Chỉ Số Thị Trường', en: 'Market Indicators' },
    'crypto-market-stats': { vi: 'Thống Kê Thị Trường Crypto', en: 'Crypto Market Statistics' },
    'live-data': { vi: 'Thời gian thực', en: 'Live data' },
    'fear-greed-index': { vi: 'Chỉ Số Sợ Hãi & Tham Lam của thị trường crypto', en: 'Fear & Greed Index of Crypto Market' },
    'btc-dominance': { vi: 'Độ Thống Trị BTC', en: 'BTC Dominance' },
    'btc-market-share': { vi: 'Thị phần BTC', en: 'BTC Market Share' },
    // Market indicators
    'market-indicators-title': { vi: 'Chỉ Số Thị Trường', en: 'Market Indicators' },
    'btc-dominance': { vi: 'Độ Thống Trị BTC', en: 'BTC Dominance' },
    'eth-dominance': { vi: 'Độ Thống Trị ETH', en: 'ETH Dominance' },
    'btc-market-share': { vi: 'Thị phần BTC', en: 'BTC Market Share' },
    'eth-market-share': { vi: 'Thị phần ETH', en: 'ETH Market Share' },
    'active-cryptos': { vi: 'Coin Hoạt Động', en: 'Active Coins' },
    'markets': { vi: 'Sàn Giao Dịch', en: 'Markets' },
    'market-cap-change': { vi: 'Thay Đổi Vốn Hóa', en: 'Market Cap Change' },
    'last-updated': { vi: 'Cập Nhật Lần Cuối', en: 'Last Updated' },
    
    // Binance Widget
    'binance-prices-title': { vi: 'Giá Crypto từ Binance', en: 'Crypto Prices from Binance' },
    
    // Fear & Greed Index classifications
    'extreme-fear': { vi: 'Sợ hãi tột độ', en: 'Extreme Fear' },
    'fear': { vi: 'Sợ hãi', en: 'Fear' },
    'neutral': { vi: 'Trung tính', en: 'Neutral' },
    'greed': { vi: 'Tham lam', en: 'Greed' },
    'extreme-greed': { vi: 'Tham lam tột độ', en: 'Extreme Greed' },
    
    // Fear & Greed Index descriptions
    'extreme-fear-desc': { vi: 'Thị trường đang trong trạng thái sợ hãi tột độ', en: 'Market is in extreme fear state' },
    'fear-desc': { vi: 'Thị trường có xu hướng giảm mạnh', en: 'Market tends to decline strongly' },
    'neutral-desc': { vi: 'Thị trường ổn định, không có xu hướng rõ ràng', en: 'Market is stable with no clear trend' },
    'greed-desc': { vi: 'Thị trường có xu hướng tăng mạnh', en: 'Market tends to rise strongly' },
    'extreme-greed-desc': { vi: 'Thị trường đang trong trạng thái tham lam tột độ', en: 'Market is in extreme greed state' },
    
    'powered-by': { vi: 'Được cung cấp bởi', en: 'Powered by' },
    'websocket-api': { vi: 'API WebSocket', en: 'WebSocket API' },
    'us-stock-indices': { vi: 'Chỉ Số Chứng Khoán Mỹ', en: 'US Stock Indices' },
    
    // Unit translations for large numbers
    'unit-trillion': { vi: ' Nghìn Tỷ', en: ' T' },
    'unit-billion': { vi: ' Tỷ', en: ' B' },
    'unit-million': { vi: ' Triệu', en: ' M' },

    // Market Analytics Page Translations
    'analytics-page-title': { vi: 'Phân Tích Tương Quan Volume & Open Interest - Crypto Dashboard', en: 'Volume & Open Interest Correlation Analytics - Crypto Dashboard' },
    'analytics-title': { vi: 'Phân Tích Tương Quan Volume Spot & Futures', en: 'Spot vs Futures Volume & Open Interest Analytics' },
    'analytics-subtitle': { vi: 'So sánh tương quan khối lượng giao dịch Spot vs Phái sinh và Vị thế mở (Open Interest) theo thời gian thực từ Binance API', en: 'Real-time correlation analysis of Spot vs Derivatives trading volume and Open Interest directly from Binance API' },
    'analytics-nav-btn': { vi: 'Phân Tích Volume & Vị Thế Mở (OI)', en: 'Volume & Open Interest Analytics' },
    'analytics-desc': { vi: 'Công cụ phân tích tương quan dòng tiền Spot - Futures, đo lường độ chênh lệch Volume và theo dõi biến động vị thế mở.', en: 'Analyze Spot vs Futures capital flows, volume delta, ratio, and track open interest fluctuations.' },
    'select-symbol': { vi: 'Chọn Cặp Giao Dịch', en: 'Select Trading Pair' },
    'custom-symbol': { vi: 'Nhập cặp khác...', en: 'Custom pair (e.g. SOLUSDT)...' },
    'timeframe': { vi: 'Khung thời gian', en: 'Timeframe' },
    'candle-limit': { vi: 'Số lượng nến', en: 'Candle Limit' },
    'auto-refresh': { vi: 'Tự động cập nhật', en: 'Auto Refresh' },
    'manual-refresh': { vi: 'Cập nhật ngay', en: 'Refresh Now' },
    'api-status': { vi: 'Trạng thái API', en: 'API Status' },
    'spot-volume-24h': { vi: 'Khối lượng Spot (24h)', en: '24h Spot Volume' },
    'futures-volume-24h': { vi: 'Khối lượng Futures (24h)', en: '24h Futures Volume' },
    'futures-spot-ratio': { vi: 'Tỷ lệ Futures / Spot', en: 'Futures / Spot Ratio' },
    'open-interest': { vi: 'Vị thế mở (Open Interest)', en: 'Open Interest (OI)' },
    'volume-correlation': { vi: 'Tương quan Volume (Pearson)', en: 'Volume Correlation (Pearson)' },
    'market-state': { vi: 'Trạng thái thị trường', en: 'Market State' },
    'high-correlation': { vi: 'Đồng thuận cao (Thị trường thực)', en: 'High Alignment (Spot-driven)' },
    'low-correlation': { vi: 'Phân kỳ / Đầu cơ phái sinh', en: 'Divergence (Speculative)' },
    'moderate-correlation': { vi: 'Tương quan trung bình', en: 'Moderate Correlation' },
    'long-buildup': { vi: 'Long Tích lũy (Giá ↑, OI ↑)', en: 'Long Build-up (Price ↑, OI ↑)' },
    'short-squeeze': { vi: 'Short Squeeze (Giá ↑, OI ↓)', en: 'Short Squeeze (Price ↑, OI ↓)' },
    'short-buildup': { vi: 'Short Tích lũy (Giá ↓, OI ↑)', en: 'Short Build-up (Price ↓, OI ↑)' },
    'long-liquidation': { vi: 'Long Thanh lý (Giá ↓, OI ↓)', en: 'Long Liquidation (Price ↓, OI ↓)' },
    'tab-price-volume': { vi: 'Giá & Khối lượng Song hành', en: 'Price & Dual Volume' },
    'tab-buy-sell-volume': { vi: 'Khối lượng Mua vs Bán Chủ Động', en: 'Taker Buy vs Sell Volume' },
    'tab-volume-delta': { vi: 'Độ lệch Volume & Tỷ lệ F/S', en: 'Volume Delta & Ratio' },
    'tab-long-short-spot': { vi: 'Vị thế Long / Short vs Volume Spot', en: 'Long / Short Positions vs Spot Vol' },
    'tab-long-short-ratio': { vi: 'Phân bổ Vị thế & Tỷ lệ Long / Short', en: 'Position Distribution & L/S Ratio' },
    'tab-open-interest': { vi: 'Vị thế mở & Giá', en: 'Open Interest & Price' },
    'tab-correlation-cvd': { vi: 'Tương quan & CVD Trượt', en: 'Correlation & Rolling CVD' },
    'tab-net-taker-delta': { vi: 'Net Delta Mua/Bán Ròng (Spot & Futures)', en: 'Net Taker Buy/Sell Delta (Spot & Futures)' },
    'long-position-card': { vi: 'Vị Thế Long (OI)', en: 'Long Position (OI)' },
    'short-position-card': { vi: 'Vị Thế Short (OI)', en: 'Short Position (OI)' },
    'buy-volume': { vi: 'Khối Lượng Mua', en: 'Buy Volume' },
    'sell-volume': { vi: 'Khối Lượng Bán', en: 'Sell Volume' },
    'buy-sell-ratio': { vi: 'Tỷ Lệ Mua / Bán', en: 'Buy / Sell Ratio' },
    'spot-buy-vol': { vi: 'Spot Mua (Taker)', en: 'Spot Buy Vol' },
    'spot-sell-vol': { vi: 'Spot Bán (Taker)', en: 'Spot Sell Vol' },
    'fut-buy-vol': { vi: 'Futures Mua (Longs)', en: 'Futures Buy Vol' },
    'fut-sell-vol': { vi: 'Futures Bán (Shorts)', en: 'Futures Sell Vol' },
    'data-breakdown-title': { vi: 'Bảng Thống Kê Chi Tiết Từng Chu Kỳ', en: 'Period-by-Period Data Breakdown' },
    'export-csv': { vi: 'Xuất dữ liệu (CSV)', en: 'Export to CSV' },
    'methodology-title': { vi: 'Cẩm Nang Phân Tích & Hướng Dẫn Đọc Lệnh (Order Flow Guide)', en: 'Analysis Playbook & Order Flow Reading Guide' },
    'client-side-note': { vi: '⚡ Toàn bộ dữ liệu được tải và tính toán trực tiếp trên trình duyệt của bạn từ Binance Public API.', en: '⚡ All data is fetched and computed directly in your browser from Binance Public APIs.' },
    'fetch-error': { vi: 'Lỗi tải dữ liệu từ Binance API. Vui lòng thử lại!', en: 'Error fetching data from Binance API. Please try again!' },
    'fetching-data': { vi: 'Đang tải dữ liệu từ Binance...', en: 'Fetching data from Binance...' },
    'candles': { vi: 'nến', en: 'candles' },

    // Order Flow & Methodology Translations
    'order-flow-guide-title': { vi: 'Cẩm Nang Phân Tích & Hướng Dẫn Đọc Lệnh (Order Flow Guide)', en: 'Analysis Playbook & Order Flow Reading Guide' },
    'playbook-title': { vi: 'Quy Trình 4 Bước Đọc Lệnh Thực Chiến (Order Flow Execution)', en: '4-Step Order Flow Execution Playbook' },
    'step-1-badge': { vi: 'BƯỚC 1', en: 'STEP 1' },
    'step-1-title': { vi: 'Xác Định Lực Khớp Tức Thời', en: 'Determine Real-Time Taker Flow' },
    'step-1-desc': { vi: 'Quan sát biểu đồ Khối lượng Mua vs Bán và Net Delta Nến. Nếu Net Delta dương đậm (Xanh lá) nghĩa là phe Mua đang chủ động đẩy lệnh Market; nếu âm (Đỏ) là phe Bán đang ép giá.', en: 'Observe Buy vs Sell Volume and Bar Net Delta. Positive (Green) indicates aggressive market buying; negative (Red) indicates aggressive market selling.' },
    'step-2-badge': { vi: 'BƯỚC 2', en: 'STEP 2' },
    'step-2-title': { vi: 'Đối Chiếu Vị Thế Mở (OI)', en: 'Cross-Reference Open Interest (OI)' },
    'step-2-desc': { vi: 'Kiểm tra biến động OI: Giá tăng mà OI tăng là tiền mới vào mở Long (Long Build-up). Nếu Giá tăng mà OI giảm thì chỉ là Short bị thanh lý/cắt lỗ (Short Squeeze - rủi ro đảo chiều cao).', en: 'Check OI changes: Price ↑ + OI ↑ signals genuine Long accumulation. Price ↑ + OI ↓ indicates short covering / squeezes with high reversal risk.' },
    'step-3-badge': { vi: 'BƯỚC 3', en: 'STEP 3' },
    'step-3-title': { vi: 'Phát Hiện Phân Kỳ CVD', en: 'Identify CVD Divergence' },
    'step-3-desc': { vi: 'Nếu Giá tạo đáy mới thấp hơn nhưng đường CVD tạo đáy cao hơn -> Phe Bán bị hấp thụ hoàn toàn bởi lệnh Limit Buy (Tín hiệu đảo chiều tăng mạnh).', en: 'If Price makes a lower low while Cumulative Volume Delta makes a higher low -> Sellers are absorbed by passive Limit buyers (Strong bullish reversal signal).' },
    'step-4-badge': { vi: 'BƯỚC 4', en: 'STEP 4' },
    'step-4-title': { vi: 'Đánh Giá Đòn Bẩy F/S', en: 'Evaluate F/S Leverage Ratio' },
    'step-4-desc': { vi: 'Tỷ lệ Futures/Spot > 4x cảnh báo thị trường đầu cơ quá mức. Đối chiếu quy mô Long/Short với Spot Vol để phòng ngừa rủi ro bẫy quét thanh lý 2 đầu.', en: 'Futures/Spot ratio > 4x warns of excessive speculation. Cross-check Long/Short positions against Spot Vol to guard against whipsaw liquidations.' },

    // Matrix Cheat Sheet
    'cheat-sheet-title': { vi: 'Bảng Tra Cứu Tín Hiệu & Hành Động Đọc Lệnh Nhanh', en: 'Quick Signal & Order Flow Cheat-Sheet Matrix' },
    'th-state': { vi: 'Trạng Thái', en: 'State' },
    'th-price': { vi: 'Giá (Price)', en: 'Price' },
    'th-taker-flow': { vi: 'Taker Flow', en: 'Taker Flow' },
    'th-oi': { vi: 'Vị Thế Mở (OI)', en: 'Open Interest (OI)' },
    'th-nature': { vi: 'Bản Chất Dòng Tiền', en: 'Underlying Flow Dynamic' },
    'th-action': { vi: 'Hành Động Khuyến Nghị', en: 'Recommended Action' },

    'long-buildup-nature': { vi: 'Dòng tiền tổ chức/trader nạp vốn mở vị thế Long mới theo xu hướng', en: 'Institutional/trader capital opening fresh Long positions following the trend' },
    'long-buildup-action': { vi: 'Ưu tiên Buy / Long theo Trend', en: 'Prioritize Buy / Long with Trend' },
    'short-squeeze-nature': { vi: 'Tăng do phe Short bị ép cắt lỗ hoặc thanh lý cưỡng bức (Hết xăng)', en: 'Rally driven by short liquidations & stop-losses (Exhaustion risk)' },
    'short-squeeze-action': { vi: 'Chốt lời Long, canh Short đảo chiều', en: 'Take profit Long, prepare for Short reversal' },
    'short-buildup-nature': { vi: 'Dòng tiền mở mới vị thế Short ồ ạt, áp lực bán đè giá quyết liệt', en: 'Aggressive capital opening fresh Short positions pushing price down' },
    'short-buildup-action': { vi: 'Ưu tiên Sell / Short theo Trend', en: 'Prioritize Sell / Short with Trend' },
    'long-liquidation-nature': { vi: 'Long bị xả thanh lý hàng loạt, giai đoạn rũ bỏ cuối cùng của đợt giảm', en: 'Long cascade liquidations, final capitulation / shakeout phase' },
    'long-liquidation-action': { vi: 'Chốt lời Short, canh bắt đáy hồi phục', en: 'Take profit Short, look for mean-reversion bounce' },

    // Metric Details
    'metrics-detail-title': { vi: 'Ý Nghĩa & Chi Tiết Các Chỉ Số Đo Lường', en: 'Metric Definitions & Theoretical Details' },
    'taker-desc': { vi: 'Đo lường trực tiếp các lệnh khớp Market. Taker Buy bao gồm mở Long mới + cắt lỗ Short; Taker Sell bao gồm mở Short mới + thanh lý Long.', en: 'Directly measures aggressive market orders. Taker Buy = fresh Longs + Short stops; Taker Sell = fresh Shorts + Long liquidations.' },
    'cvd-desc': { vi: 'Tích lũy chênh lệch (Buy - Sell). CVD phân kỳ với giá là chỉ báo sớm đáng tin cậy nhất về việc cá mập đang âm thầm gom hoặc xả hàng.', en: 'Accumulated (Buy - Sell) delta. Divergence against price is the most reliable early indicator of smart-money accumulation or distribution.' },
    'ls-pos-desc': { vi: 'Tỷ lệ tài khoản hoặc vị thế mở Long vs Short. Tỷ lệ lệch trên 70% là tín hiệu thị trường quá nghiêng về một phía (Crowded Trade), dễ xảy ra bẫy quét thanh lý.', en: 'Ratio of Long vs Short positions. A skew above 70% indicates a crowded trade, highly vulnerable to liquidation cascades.' },
    'long-spot-desc': { vi: 'Đo lường quy mô vị thế Long so với thanh khoản Spot. Tỷ lệ > 3x - 5x cảnh báo thanh khoản Spot có thể không hấp thụ nổi nếu xảy ra chuỗi thanh lý Long đột ngột.', en: 'Measures Long positions against Spot liquidity. A ratio > 3x-5x warns that Spot depth may fail to absorb cascading Long liquidations.' },
    'short-spot-desc': { vi: 'Đo lường quy mô vị thế Short so với thanh khoản Spot. Tỷ lệ > 3x - 5x là tín hiệu cảnh báo rủi ro bùng nổ Short Squeeze cực mạnh khi giá đảo chiều tăng.', en: 'Measures Short positions against Spot liquidity. A ratio > 3x-5x warns of explosive Short Squeezes upon price reversal.' },
    'corr-desc': { vi: 'Hệ số tương quan khối lượng giữa Spot và Futures (14 chu kỳ). > 0.7 thể hiện dòng tiền thực giao ngay đồng thuận; < 0.3 là dấu hiệu đầu cơ phái sinh đơn lẻ.', en: '14-period rolling volume correlation between Spot and Futures. > 0.7 reflects genuine spot backing; < 0.3 indicates isolated derivatives speculation.' },

    // Data table columns
    'th-time': { vi: 'Thời gian', en: 'Time' },
    'th-close-price': { vi: 'Giá Đóng Cửa', en: 'Close Price' },
    'th-long-pos': { vi: 'Vị thế Long ($)', en: 'Long Pos ($)' },
    'th-short-pos': { vi: 'Vị thế Short ($)', en: 'Short Pos ($)' },
    'th-ls-ratio': { vi: 'Tỷ lệ L/S', en: 'L/S Ratio' },
    'th-fs-ratio': { vi: 'Tỷ lệ F/S', en: 'F/S Ratio' }
    };
    return translations_data;
}

// Auto-register translations when this script loads
(function() {
    // Function to try registering translations
    function tryRegisterTranslations() {
        try {
            const translationsData = get_translations_data();
            
            // Method 1: Use setTranslations if available
            if (typeof window.setTranslations === 'function') {
                window.setTranslations(translationsData);
                console.log('✅ Translations registered via setTranslations');
                return true;
            }
            
            // Method 2: Set global variables directly
            window.translations_data = translationsData;
            window.translations = translationsData;
            console.log('✅ Translations set globally');
            
            return false; // setTranslations not available yet
        } catch (e) {
            console.warn('Could not register translations:', e);
            return false;
        }
    }
    
    // Try immediately first
    if (tryRegisterTranslations()) {
        return; // Success, we're done
    }
    
    // If failed, wait for DOM ready and retry
    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', function() {
            setTimeout(tryRegisterTranslations, 100);
        });
    } else {
        // DOM already ready, retry after a short delay
        setTimeout(tryRegisterTranslations, 100);
    }
    
    // Also listen for a custom event in case language-toggle.js loads later
    window.addEventListener('languageToggleReady', function() {
        tryRegisterTranslations();
    });
})();

