[build]
# Remove jobs = 0 as it causes issues

[net]
retry = 3  # Faster retries
git-fetch-with-cli = true

[target.x86_64-unknown-linux-musl]
linker = "rust-lld"
rustflags = ["-C", "target-feature=+crt-static"]

[target.x86_64-unknown-linux-gnu]
linker = "cc"

# Production optimizations for Railway
[env]
RUST_LOG = { value = "warn", force = false }  # Less logging for performance
TOKIO_THREAD_STACK_SIZE = { value = "8388608", force = false }  # 8MB stack
MALLOC_ARENA_MAX = { value = "4", force = false }  # Memory optimization

# Release profile optimizations
[profile.release]
lto = "fat"         # Full Link Time Optimization
codegen-units = 1   # Single codegen unit for max optimization
panic = "abort"     # Abort on panic for smaller binary
strip = "symbols"   # Strip debug symbols

[profile.dev.package."*"]
opt-level = 2
