[build]
jobs = 2

[net]
retry = 5
git-fetch-with-cli = true
download-buffer-size = "64MB"

[target.x86_64-unknown-linux-musl]
linker = "rust-lld"
rustflags = ["-C", "target-feature=+crt-static"]

[target.x86_64-unknown-linux-gnu]
linker = "cc"

# Merged from .cargo/config (deprecated file name)
[env]
RUST_LOG = { value = "info", force = false }
TOKIO_THREAD_STACK_SIZE = { value = "4194304", force = false }
RAYON_NUM_THREADS = { value = "0", force = false }

[profile.dev.package."*"]
opt-level = 2
