function get_translations_data()
{
    const translations_data = {
    // Navigation, Header & Breadcrumbs
    'home': { vi: 'Trang chủ', en: 'Home' },
    'analytics-nav-btn': { vi: 'Phân Tích Volume & OI', en: 'Volume & OI Analytics' },
    'view-report-history': { vi: 'Lịch Sử Báo Cáo', en: 'View Report History' },
    'breadcrumb-home': { vi: 'Trang chủ', en: 'Home' },
    'breadcrumb-reports': { vi: 'Lịch Sử Báo Cáo', en: 'Report History' },
    'site-title': { vi: 'Toàn Cảnh Thị Trường Tiền Mã Hóa', en: 'Crypto Market Overview' },
    'analysis-summary': { vi: 'Bài phân tích và tổng hợp', en: 'Analysis and summary' },
    'created-at': { vi: 'Tạo lúc', en: 'Created at' },
    'report-table-of-contents': { vi: '📋 Mục lục Báo cáo', en: '📋 Report Table of Contents' },
    'print-report': { vi: 'In Báo cáo', en: 'Print Report' },
    'report-display': { vi: 'Hiển thị báo cáo', en: 'Displaying report' },
    'close': { vi: 'Đóng', en: 'Close' },

    // Summary Cards / Market Metrics
    'btc-price': { vi: 'Giá BTC', en: 'BTC Price' },
    'market-cap': { vi: 'Tổng Vốn Hóa', en: 'Market Capitalization' },
    'volume-24h': { vi: 'Khối Lượng Giao Dịch 24h', en: '24h Trading Volume' },
    'fear-greed-title': { vi: 'Chỉ số Sợ hãi & Tham lam', en: 'Fear & Greed Index' },
    'rsi-btc-title': { vi: 'Chỉ số Sức mạnh Tương đối (RSI 14) - BTC', en: 'Relative Strength Index (RSI 14) - BTC' },
    'bitcoin': { vi: 'Bitcoin', en: 'Bitcoin' },
    'altcoins': { vi: 'Altcoins', en: 'Altcoins' },
    'whole-market': { vi: 'Toàn bộ thị trường', en: 'Whole market' },

    // Classification & Indicator Badges
    'extreme-fear': { vi: 'Sợ hãi Tột độ', en: 'Extreme Fear' },
    'fear': { vi: 'Sợ hãi', en: 'Fear' },
    'neutral': { vi: 'Trung lập', en: 'Neutral' },
    'greed': { vi: 'Tham lam', en: 'Greed' },
    'extreme-greed': { vi: 'Tham lam Tột độ', en: 'Extreme Greed' },
    'extreme-fear-desc': { vi: 'Thị trường đang trong trạng thái sợ hãi tột độ', en: 'Market is in extreme fear state' },
    'fear-desc': { vi: 'Thị trường có xu hướng giảm mạnh', en: 'Market tends to decline strongly' },
    'neutral-desc': { vi: 'Thị trường ổn định, không có xu hướng rõ ràng', en: 'Market is stable with no clear trend' },
    'greed-desc': { vi: 'Thị trường có xu hướng tăng mạnh', en: 'Market tends to rise strongly' },
    'extreme-greed-desc': { vi: 'Thị trường đang trong trạng thái tham lam tột độ', en: 'Market is in extreme greed state' },
    'oversold': { vi: 'Quá bán', en: 'Oversold' },
    'overbought': { vi: 'Quá mua', en: 'Overbought' },

    // Disclaimers
    'disclaimer-title': { vi: 'Tuyên bố miễn trừ trách nhiệm:', en: 'Disclaimer:' },
    'disclaimer-body': { vi: 'Nội dung và phân tích trên trang này chỉ mang tính chất tham khảo và không cấu thành lời khuyên đầu tư. Mọi quyết định đầu tư là trách nhiệm của người đọc.', en: 'The content and analysis on this site are for informational purposes only and do not constitute investment advice. All investment decisions are the responsibility of the reader.' },
    'ai-generated-disclaimer': { vi: 'Báo cáo được tạo tự động bởi trí tuệ nhân tạo (AI) dựa trên dữ liệu thị trường thời gian thực. Không đảm bảo tính chính xác tuyệt đối.', en: 'Reports are automatically generated by artificial intelligence (AI) based on real-time market data. Absolute accuracy is not guaranteed.' },

    // Status, Realtime & Error Handling
    'refresh-data': { vi: 'Cập nhật dữ liệu', en: 'Refresh Data' },
    'refreshing': { vi: 'Đang cập nhật...', en: 'Refreshing...' },
    'connecting': { vi: 'Đang kết nối...', en: 'Connecting...' },
    'reconnecting': { vi: 'Đang kết nối lại...', en: 'Reconnecting...' },
    'real-time-connected': { vi: 'Kết nối thời gian thực', en: 'Real-time connected' },
    'disconnected': { vi: 'Mất kết nối', en: 'Disconnected' },
    'connection-lost': { vi: 'Mất kết nối', en: 'Connection lost' },
    'connection-error': { vi: 'Lỗi kết nối', en: 'Connection error' },
    'connection-failed': { vi: 'Không thể kết nối', en: 'Connection failed' },
    'data-updated': { vi: 'Dữ liệu đã được cập nhật', en: 'Data updated successfully' },
    'refresh-failed': { vi: 'Lỗi cập nhật dữ liệu', en: 'Failed to refresh data' },
    'last-update': { vi: 'Cập nhật lần cuối', en: 'Last updated' },
    'loading': { vi: 'Đang tải...', en: 'Loading...' },
    'error-loading-data': { vi: 'Lỗi tải dữ liệu', en: 'Error loading data' },
    'error-fetching-data': { vi: 'Lỗi tải dữ liệu', en: 'Error fetching data' },
    'no-report-created': { vi: 'Chưa có báo cáo nào được tạo.', en: 'No reports have been created yet.' },
    'please-upload': { vi: 'Vui lòng sử dụng trang tải lên để tạo báo cáo đầu tiên của bạn.', en: 'Please use the upload page to create your first report.' },

    // Unit translations for large numbers
    'unit-trillion': { vi: ' Nghìn Tỷ', en: ' T' },
    'unit-billion': { vi: ' Tỷ', en: ' B' },
    'unit-million': { vi: ' Triệu', en: ' M' }
    };
    return translations_data;
}

// Auto-register translations when this script loads
(function() {
    function tryRegisterTranslations() {
        try {
            const translationsData = get_translations_data();
            
            // Method 1: Use setTranslations if available
            if (typeof window.setTranslations === 'function') {
                window.setTranslations(translationsData);
                console.log('✅ Report View Translations registered via setTranslations');
                return true;
            }
            
            // Method 2: Set global variables directly
            window.translations_data = translationsData;
            window.translations = translationsData;
            console.log('✅ Report View Translations set globally');
            
            return false;
        } catch (e) {
            console.warn('Could not register translations:', e);
            return false;
        }
    }
    
    // Try immediately first
    if (tryRegisterTranslations()) {
        return;
    }
    
    // If failed, wait for DOM ready and retry
    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', function() {
            setTimeout(tryRegisterTranslations, 100);
        });
    } else {
        setTimeout(tryRegisterTranslations, 100);
    }
    
    // Also listen for a custom event in case language-toggle.js loads later
    window.addEventListener('languageToggleReady', function() {
        tryRegisterTranslations();
    });
})();
